### ISSUE TITLE
[Question] Any plans to update for v11?

### ISSUE THREAD

**Issue by steveculshaw** [illandril/FoundryVTT-token-hud-scale#125]
[Question] Any plans to update for v11?

**Comment by illandril** [comment]
I will be testing v11 and upgrading all of my modules as needed once a few more systems are updated. I'm not aware of anything in v11 that was likely to break this module, so it might already work.

**Comment by steveculshaw** [comment]
Thanks for the update.

I'll report anything I find, but looking good so far.
