### ISSUE TITLE
Feature Request: Scale based on Zoom Factor. 

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#14]
In contrast with static zoom level, this option modifies the current static zoom level to maintain approximate size when zooming far out. For example, if scene zoom is 0.5, increase Token HUD scale by 20%, 0.3 for 50%, 0.2 for 75% etc.

**Comment by illandril** [comment]
That is the exact behavior I wanted when first making this module, but I had initially approached it from a "stop the stupid scaling in the first place" direction, which would require way too much work for it to be worth it.

Approaching it from the other direction, and scaling in reverse to counteract the unnecessary initial scaling, however, is very doable (despite it being a complete waste of CPU/GPU time to triple scale just to end up with effectively no scale).
