### ISSUE TITLE
Static Size HUD causes massive framedrop < 10 even when HUD not shown

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#15]
Thanks for implementing #14 but there's a massive issue with it at the moment due to recalculation happening anytime the user zooms, causing massive frame drops. When HUD is not shown the scaling should not trigger. Also, maybe a lazy rescale logic where the HUD rescales seconds after the zoom ends, or maybe doesn't rescale while zooming but only when opening the HUD.

**Comment by illandril** [comment]
The rescale logic isn't doing anything that should use anything anywhere close to a substantial amount of resources, and I cannot cause even the slightest frame rate drop even with the HUD open on my end - it should take less than 1ms even on a very weak computer.. but I'll reduce the scaling frequency anyway so it happens only when the HUD is open and at most once every 100ms even if the HUD is open.
