### ISSUE TITLE
Icons are duplicated in PF2E 1.13.1

### ISSUE THREAD

**Issue by JamzTheMan** [illandril/FoundryVTT-token-hud-scale#20]
Icons looks like they are running both horizontally and vertically causing duplicate icons.

![image](https://user-images.githubusercontent.com/8051654/116569455-045f8e80-a8cf-11eb-9dd8-6dde980ddca2.png)

**Comment by illandril** [comment]
I cannot reproduce this on PF2E 1.13.2..
If you can still reproduce this on the latest PF2E, please let me know what other modules you have installed, as well as any settings you have for any modules and/or PF2E that you think might be related to these icons.

**Comment by JamzTheMan** [comment]
There must have been another module that was cross conflicting with yours as I can no longer replicate it after the last batch of module updates.  I'll reopen if it ever comes back.
