### ISSUE TITLE
[BUG] Option for static UI is reversed

### ISSUE THREAD

**Issue by ghost** [illandril/FoundryVTT-token-hud-scale#25]
The option for static UI changes seems to be reversed. It´s dynamic when enabled and static when disabled.
See foundry discord message for example:
https://discord.com/channels/170995199584108546/713259405667205193/865898486217703454

**Comment by illandril** [comment]
Based on your screenshots and my testing to confirm everything is still working as intended, I believe this is a "the English language is imprecise and the same term can be taken to mean many different things" issue.

My use of "Static" and "Dynamic" is in reference to you, the player.
When "Static Sized HUD" is checked, its size is "Static", as in it takes up the same amount of space on the screen, regardless of how much you zoom in or out on the map.
When "Static Sized HUD" is unchecked, its size is "Dynamic", just as the size of tokens is also "Dynamic". As you zoom in, it gets larger. When you zoom out, it gets smaller.

I'm open to renaming the option and/or adjusting the help text if you have a suggestion on something that would be more clear without being overly verbose, but I don't have any better ideas for terminology.
