### ISSUE TITLE
[BUG] Tokens with Conditions cannot be selected once dragged to map

### ISSUE THREAD

**Issue by DariusWolfe** [illandril/FoundryVTT-token-hud-scale#27]
**Describe the bug**
An actor with Conditions/Effects, if dragged into a scene, cannot be interacted with normally. Clicking the token does not select it, nor does mousing over it bring up the normal HUD. You can drag-select the token, but the HUD never appears. Removing conditions from the Actor and dragging it back allows the token to be interacted with as normal, and you can interact with it if the Condtions/Effects are added to the token once it's on the map; Refreshing in both cases acts the same as dragging the token to the map again

**What steps did you take before experiencing the problem?**
1. Install a System (I tested with 5e and PF2e)
2. Install a World
3. Create a Scene
4. Create an Actor (I used a Player Character)
5. Drag the Actor to the scene to create a Token
6. Add Condtions/Effects to the token
7. Delete the token
8. Drag the Actor to the scene again

**Screenshots**

**Foundry Versions**
 - Version of this module: 1.4.2
 - Foundry Version: 9 Build 238
 - System Name and Version: D&D 5e/Pathfinder 2e
 - Browser Name and Version: FVTT Built-in Browser

**What other modules did you have active when experiencing this issue (include both names and versions)?**
No other modules enabled

**Additional context**
Add any other context about the problem here (ex. any settings for Foundry, the System, and/or Modules that you think may be related).

**Comment by illandril** [comment]
FYI: I am not expecting to have time to test any of my modules for FoundryVTT v9 and make any necessary changes for that update until after the new year, so don't expect this to get fixed for a couple of weeks at least.
