### ISSUE TITLE
[BUG] Canvas drawing failed for the tokenlayer

### ISSUE THREAD

**Issue by notgithub111** [illandril/FoundryVTT-token-hud-scale#28]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at updateEffectScales (effect-scaler.js:42)
    at TokenPF.Token.drawEffects (effect-scaler.js:7)

This is on the latest stable release v9 build 238

This is with all other modules disabled. [Microsoft Windows 10 Home, 10.0.19042 Build 19042, 32 GB RAM]
After this error, which not happens 100%, I cannot click or right-click on a token.
I can only select a token by dragging a square over the token but even if selected I cannot do anything with it since I cannot reveal the resource values, status effects, etc....

**Comment by illandril** [comment]
FYI: I am not expecting to have time to test any of my modules for FoundryVTT v9 and make any necessary changes for that update until after the new year, so don't expect this to get fixed for a couple of weeks at least.

**Comment by notgithub111** [comment]
no worries, life happens, love the module as I have a very high res monitor and it keeps the HUD from being tiny, so thanks for the module and the work!

**Comment by DukeOfArgyle** [comment]
Hey @illandril, I was reading the API and I think I found the change. I managed to fix this locally, so I've submitted my patch if you want it.

**Comment by mcglincy** [comment]
FWIW, I locally applied @DukeOfArgyle's patch from #29 and it fixes the hud scaler errors I was seeing w/ Foundry v9.

**Comment by BlackBadger777** [comment]
Is there a way to apply @DukeOfArgyle 's patch while using the Forge? Or should I wait until @illandril has released an official patch? I'm not well versed in module management, so any advice would be appreciated. 

I rely heavily on this module's scaling function - I use very large maps and don't want to scroll in and out all the time because the Token HUD is so small.
