### ISSUE TITLE
[FEATURE] Integration with libwrapper for better compatibility with other modules

### ISSUE THREAD

**Issue by p4535992** [illandril/FoundryVTT-token-hud-scale#32]
**Is your feature request related to a problem? Please describe.**

For a best experience and compatibility with other modules  is recommended to use the libWrapperModule for the override of these method:

- Token.prototype.drawEffects
- TokenHUD.prototype.setPosition

Here a example of usage:
```
libWrapper.register(moduleName, "Token.prototype.drawEffects", TokenPrototype.DrawEffectsHandler, "WRAPPER");
libWrapper.register(moduleName, "TokenHUD.prototype.setPosition", TokenHUDPrototypeSetPositionHandler, "WRAPPER");
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**What system(s) do you want this feature to work with?**
Add the names of the system or systems you use here.

**What other modules do you use that you want to ensure work well with this feature?**
Add the names of other modules you use here.

**Additional context**

**Comment by illandril** [comment]
I am not going to require people to install a module I have no control over unless there is an actual problem it solves that I can't reasonably solve within my own module.
Unless you have an actual example of a module that isn't compatible with Illandril's Token HUD Scaler (except for libwrapper itself being excessively pushy about getting everyone to use their module, which I consider to be a bug in libwrapper), I'm not going to do anything.

**Comment by p4535992** [comment]
kk ty for the response
