### ISSUE TITLE
Icon 'Above the Token, in rows' does not work

### ISSUE THREAD

**Issue by TheRarita** [illandril/FoundryVTT-token-hud-scale#36]
**Describe the bug**
When 'Effect Icons Layout' is set to 'Above the Token, in rows', the icons will show up above the token only for a moment but once you hover over the token, the icon will jump back in the token as per default behavior

**What steps did you take before experiencing the problem?**
1. Set 'Effect Icons Layout' to 'Above the Token, in rows' and save
2. Add Effect to a token, see that it is above the token
3. Hover over the token, the icon moved into the token

**What did you expect to happen?**
The icons to stay above the token at all times

**What happened instead?**
The icon moved inside of the token on hover

**Screenshots**
https://user-images.githubusercontent.com/51272447/190199825-b8a53918-8bbb-4d43-a8a1-8cdeca81b8ce.mp4

**Foundry Versions**
 - Version of this module: 2.1.0
 - Foundry Version: v10.285
 - System Name and Version: DnD 5e 2.0.2
 - Browser Name and Version: Chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
Libwrapper latest, Find the culprit latest

**Comment by illandril** [comment]
You need to actually fill out the form for me to know what your problem is.

**Comment by TheRarita** [comment]
Sorry, I had it filled out and it bugged on me (I fucked up)... I edited the form, sorry.
