### ISSUE TITLE
[BUG] Darken Token HUD Scaler kills the CSS for pressed invisibility button

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#39]
FVTT 10 , PF2 latest, with and without Dorako UI, Confirmed with Culprit. 

Seems that when Darken Token HUD Background is on, the Invisibility button (the mystery man) will not properly switch to ON state when active, and appear as if inactive.

**Comment by illandril** [comment]
I cannot reproduce this. If you still see this issue, please update this issue with additional details.
