### ISSUE TITLE
Issue in 0.7.8, with tokens receiving multiple conditions in PF2

### ISSUE THREAD

**Issue by apoapostolov** [illandril/FoundryVTT-token-hud-scale#8]
In PF2, some conditions automatically set other conditions. I.e. when you become grabbed you become immobilized and flat-footed. Your mod is making such conditions apply their secondary conditions twice, and icons become full with conditions.

This only applies to the condition icons, not the conditions. 

![image](https://user-images.githubusercontent.com/4083812/101507623-6b5fc380-397f-11eb-8281-e871a78a036c.png) 
![image](https://user-images.githubusercontent.com/4083812/101507676-7d416680-397f-11eb-802d-fac196566302.png)

**Comment by illandril** [comment]
I will likely not have time to look into this for another week or two at least.
If anyone sees this and has an interest in working on it, please comment before you start working on it to minimize the risk of two people working on this at the same time. I will assign this issue to myself before I start working on it if nobody else comes forward with a reasonable pull request before I get to it.

**Comment by illandril** [comment]
I have attempted to reproduce this using Foundry 0.7.9 and Pathfinder 2nd Edition 1.10.31.3122, but cannot. @apoapostolov if you can still reproduce this with the latest Foundry and Pathfinder 2 system versions, please let me know. Please let me know specifically which version of Foundry and Pathfinder 2 you see this with, as well as which other modules you have active.
